# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 410e2bb8df6246155282376942fb181354d018144d63a018db4a6196f430aafb68f334093eb5c3e758dfbc5190025d9b37370cdb5378f6858717148c1f15c757

test:
  secret_key_base: 13324e4de548050b2c6c6d23d573981b031e18db63a1636ca55dec58c53fb1b5739826bda4b41aab9e61ad793439ead07b0e2becff466c14f103f3791c355fd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
